build:
  image: golang:1.5
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-webhook
    when:
      branch: master

plugin:
  name: Webhook
  desc: Send build status notifications via Webhook
  type: notify
  image: plugins/drone-webhook
  labels:
    - notify
    - webhook
    - rest
    - json
    - hook
