workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-webhook

pipeline:
  build:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make build
      - make test

  docker:
    repo: plugins/drone-webhook
    storage_driver: overlay
    tag: latest
    when:
      branch: master
      event: push

plugin:
  name: Webhook
  desc: Send build status notifications via Webhook
  type: notify
  image: plugins/drone-webhook
  labels:
    - notify
    - webhook
    - rest
    - json
    - hook
