workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-webhook

pipeline:
  test:
    image: golang:1.9
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build_linux_amd64:
    image: golang:1.9
    commands:
      - sh .drone.sh

  publish_linux_amd64:
    image: plugins/docker
    repo: plugins/webook
    tags: [ latest, 1.0.0, 1.0, 1 ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    when:
      branch: master
      event: push

  publish_linux_arm64:
    image: plugins/docker
    repo: plugins/webhook
    tags: [ linux-arm64 ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm64
    when:
      branch: master
      event: push

  publish_linux_arm:
    image: plugins/docker
    repo: plugins/webhook
    tags: [ linux-arm ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm
    when:
      branch: master
      event: push
